### ISSUE TITLE
ReferenceError: gapi is not defined

### ISSUE THREAD

**Issue by ankon** [mtanda/grafana-google-calendar-datasource#6]
When creating the data source and pressing 'save & test' in Grafana 4.5.2 I see 'Testing...' in Grafanas UI, but then nothing happens. The console logs:
~~~~
ReferenceError: gapi is not defined
    at GoogleCalendarDatasource.load (https://grafana.internal.collaborne.com/public/plugins/mtanda-google-calendar-datasource/datasource.js?bust=1506672523074:58:13)
    at GoogleCalendarDatasource.testDatasource (https://grafana.internal.collaborne.com/public/plugins/mtanda-google-calendar-datasource/datasource.js?bust=1506672523074:70:18)
    at eval (https://grafana.internal.collaborne.com/public/app/features/plugins/ds_edit_ctrl.js?bust=1506672523074:4:2280)
    at a.withNoBackendCache (https://grafana.internal.collaborne.com/public/app/boot.e4836696.js:55:4882)
    at eval (https://grafana.internal.collaborne.com/public/app/features/plugins/ds_edit_ctrl.js?bust=1506672523074:4:2241)
    at i (https://grafana.internal.collaborne.com/public/app/boot.e4836696.js:61:3972)
    at https://grafana.internal.collaborne.com/public/app/boot.e4836696.js:61:4394
    at o.$eval (https://grafana.internal.collaborne.com/public/app/boot.e4836696.js:61:11549)
    at o.$digest (https://grafana.internal.collaborne.com/public/app/boot.e4836696.js:61:10022)
    at https://grafana.internal.collaborne.com/public/app/boot.e4836696.js:61:11636 Possibly unhandled rejection: {}
(anonymous) @ boot.e4836696.js:60
(anonymous) @ boot.e4836696.js:60
k @ boot.e4836696.js:61
$eval @ boot.e4836696.js:61
$digest @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:61
f @ boot.e4836696.js:59
(anonymous) @ boot.e4836696.js:59
setTimeout (async)
k.defer @ boot.e4836696.js:59
$evalAsync @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:61
l @ boot.e4836696.js:61
n @ boot.e4836696.js:61
m @ boot.e4836696.js:61
resolve @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:53
O @ boot.e4836696.js:6
K @ boot.e4836696.js:6
y.when @ boot.e4836696.js:6
v.run @ boot.e4836696.js:6
a._drain @ boot.e4836696.js:5
drain @ boot.e4836696.js:5
b @ boot.e4836696.js:5
characterData (async)
(anonymous) @ boot.e4836696.js:5
a.run @ boot.e4836696.js:5
a.enqueue @ boot.e4836696.js:5
w.when @ boot.e4836696.js:6
t.chain @ boot.e4836696.js:6
b.then @ boot.e4836696.js:6
(anonymous) @ boot.e4836696.js:7
import @ boot.e4836696.js:6
(anonymous) @ boot.e4836696.js:6
loadDatasource @ boot.e4836696.js:53
get @ boot.e4836696.js:53
a.testDatasource @ ds_edit_ctrl.js?bust=1506672523074:4
(anonymous) @ ds_edit_ctrl.js?bust=1506672523074:4
i @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:61
$eval @ boot.e4836696.js:61
$digest @ boot.e4836696.js:61
$apply @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:61
f @ boot.e4836696.js:59
(anonymous) @ boot.e4836696.js:59
setTimeout (async)
k.defer @ boot.e4836696.js:59
x @ boot.e4836696.js:61
$applyAsync @ boot.e4836696.js:61
i @ boot.e4836696.js:60
t @ boot.e4836696.js:60
w.onload @ boot.e4836696.js:60
XMLHttpRequest.send (async)
(anonymous) @ boot.e4836696.js:60
w @ boot.e4836696.js:60
k @ boot.e4836696.js:60
i @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:61
$eval @ boot.e4836696.js:61
$digest @ boot.e4836696.js:61
$apply @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:61
f @ boot.e4836696.js:59
(anonymous) @ boot.e4836696.js:59
setTimeout (async)
k.defer @ boot.e4836696.js:59
x @ boot.e4836696.js:61
$applyAsync @ boot.e4836696.js:61
i @ boot.e4836696.js:60
t @ boot.e4836696.js:60
w.onload @ boot.e4836696.js:60
XMLHttpRequest.send (async)
(anonymous) @ boot.e4836696.js:60
w @ boot.e4836696.js:60
k @ boot.e4836696.js:60
i @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:61
$eval @ boot.e4836696.js:61
$digest @ boot.e4836696.js:61
$apply @ boot.e4836696.js:61
(anonymous) @ boot.e4836696.js:63
dispatch @ boot.e4836696.js:57
q.handle @ boot.e4836696.js:57
~~~~

Browser is Chrome 63.0.3218.0 (Official Build) dev (64-bit) on Linux.

**Comment by mtanda** [comment]
Not sure why it doesn't work, but just porting initialize code from another plugin, it seems work.

Please try this version.
https://github.com/mtanda/grafana-google-calendar-datasource/commit/b164a3896703fe7a344bf5632b94c7492f6e512e

**Comment by ankon** [comment]
Ok, that seems to fix the error indeed.

Right now I can configure the data source in Firefox, but in Chrome the popup seems to fail to pop up. That's good enough for me right now, I'm suspecting the popup is blocked by some local settings.

Will you create a new release from this?

**Comment by mtanda** [comment]
Sure, I request to register new version.
https://github.com/grafana/grafana-plugin-repository/pull/175
